### Sumiran Rai
### Regd. No. 0 24040208007
### Deep Learning Lab 1

### List

In [2]:
a = [1.0, 2.0, 1.0]

In [3]:
a[0]

1.0

In [4]:
a[2] = 3.0

In [5]:
a

[1.0, 2.0, 3.0]

### Constructing our first tensors

In [6]:
import torch
a = torch.ones(3) # Creates a one-dimensional tensor of size 3 filled with 1s

C:\Users\sumir\AppData\Roaming\Python\Python312\site-packages\torch\utils\_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(


In [7]:
a[1]

tensor(1.)

In [8]:
float(a[1])

1.0

In [9]:
a[2] = 2.0
a

tensor([1., 1., 2.])

### Essence of tensors

In [10]:
# PyTorch tensors or NumPy arrays are contiguous memor blocks containing unboxec C numeric types rather than Python objects. Each element is a 32-bit float.

In [11]:
points = torch.zeros(6) # Using.zeros is just a way to get an appropriately sized array.
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [12]:
 # We can also pass a Python list to the constructor, to the same effect:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [13]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]]) #2D tensor
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points.shape

torch.Size([3, 2])

In [16]:
# We could also use zeros or ones to initialize the tensor, providing the size as a tuple
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [17]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
# Now we can access an individual element in the tensor using two indices.
points[0, 1]

tensor(1.)

In [18]:
# We can also access the first element in the tensor as we did before to get the 2D coordinates of the first point
points[0]

tensor([4., 1.])

### Indexing tensors

In [19]:
 some_list = list(range(6))
 some_list[:]
 some_list[1:4]
 some_list[1:]
 some_list[:4]
 some_list[:-1]
 some_list[1:4:2]

[1, 3]

In [20]:
 # In[54]:
 points[1:]
 points[1:, :]
 points[1:, 0]
 points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [21]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [22]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [23]:
 img_gray_naive = img_t.mean(-3)
 batch_gray_naive = batch_t.mean(-3)
 img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [24]:
 unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
 img_weights = (img_t * unsqueezed_weights)
 batch_weights = (batch_t * unsqueezed_weights)
 img_gray_weighted = img_weights.sum(-3)
 batch_gray_weighted = batch_weights.sum(-3)
 batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [25]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [26]:
 weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
 weights_named

C:\Users\sumir\AppData\Local\Temp\ipykernel_31088\2040007778.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\c10/core/TensorImpl.h:1938.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [27]:
 img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
 batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
 print("img named:", img_named.shape, img_named.names)
 print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [28]:
weights_aligned = weights_named.align_as(img_named)
 weights_aligned.shape, weights_aligned.names

IndentationError: unexpected indent (1483852383.py, line 2)

In [ ]:
 gray_named = (img_named * weights_aligned).sum('channels')
 gray_named.shape, gray_named.names

NameError: name 'weights_aligned' is not defined

In [ ]:
 gray_named = (img_named[..., :3] * weights_named).sum('channels')

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

In [ ]:
 gray_plain = gray_named.rename(None)
 gray_plain.shape, gray_plain.names

NameError: name 'gray_named' is not defined

In [ ]:
 double_points = torch.ones(10, 2, dtype=torch.double)
 short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [ ]:
 short_points.dtype

torch.int16

In [ ]:
double_points = torch.zeros(10, 2).double()
 short_points = torch.ones(10, 2).short()

IndentationError: unexpected indent (3992480436.py, line 2)

In [ ]:
 double_points = torch.zeros(10, 2).to(torch.double)
 short_points = torch.ones(10, 2).to(dtype=torch.short)


In [ ]:
 points_64 = torch.rand(5, dtype=torch.double)
 points_short = points_64.to(torch.short)
 points_64 * points_short # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [ ]:
 a = torch.ones(3, 2)
 a_t = torch.transpose(a, 0, 1)

In [ ]:
 a.shape, a_t.shape

In [ ]:
 a = torch.ones(3, 2)
 a_t = a.transpose(0, 1)
 a.shape, a_t.shape

In [ ]:
 points = torch.tensor([[4.0,1.0], [5.0, 3.0], [2.0, 1.0]])
 points.storage()

In [ ]:
 points_storage = points.storage()
 points_storage[0]

In [ ]:
 points.storage()[1]

In [ ]:
 points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
 points_storage = points.storage()
 points_storage[0] = 2.0
 points

In [ ]:
 a = torch.ones(3, 2)

In [ ]:
 a.zero_()
 a

In [ ]:
 points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
 second_point = points[1]
 second_point.storage_offset()

In [ ]:
second_point.size()

In [ ]:
second_point.shape

In [ ]:
 points.stride()

In [ ]:
 second_point = points[1]
 second_point.size()

In [ ]:
 second_point.storage_offset()

In [ ]:
 second_point.stride()

In [ ]:
 points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
 second_point = points[1]
 second_point[0] = 10.0
 points

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
 second_point = points[1].clone()
 second_point[0] = 10.0
 points

In [ ]:
 points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
 points

In [ ]:
 points_t = points.t()
 points_t

In [ ]:
id(points.storage()) == id(points_t.storage())

In [ ]:
 points.stride()

In [ ]:
points_t.stride()

In [ ]:
 some_t = torch.ones(3, 4, 5)
 transpose_t = some_t.transpose(0, 2)
 some_t.shape

In [ ]:
 transpose_t.shape

In [ ]:
some_t.stride()

In [ ]:
 transpose_t.stride()

In [ ]:
 points.is_contiguous()


NameError: name 'points' is not defined

In [29]:
 points_t.is_contiguous()

NameError: name 'points_t' is not defined

In [ ]:
 points = torch.tensor([[4.0,1.0], [5.0, 3.0], [2.0, 1.0]])
 points_t =points.t()
 points_t

In [ ]:
 points_t.storage()

In [ ]:
 points_t.stride()

In [ ]:
 points_t_cont = points_t.contiguous()
 points_t_cont

In [ ]:
 points_t_cont.stride()

In [ ]:
 points_t_cont.storage()

In [ ]:
 points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [ ]:
 points_gpu = points.to(device='cuda')

In [ ]:
 points_gpu = points.to(device='cuda:0')

In [ ]:
 points = 2 * points
 points_gpu = 2 * points.to(device='cuda')

In [ ]:
 points_gpu = points_gpu + 4

In [ ]:
points_cpu = points_gpu.to(device='cpu')

In [ ]:
points_gpu = points.cuda()
 points_gpu = points.cuda(0)
 points_cpu = points_gpu.cpu()

In [ ]:
points = torch.ones(3, 4)
 points_np = points.numpy()
 points_np

In [ ]:
 points = torch.from_numpy(points_np)

In [ ]:
 torch.save(points, '../data/p1ch3/ourpoints.t')

In [ ]:
 with open('../data/p1ch3/ourpoints.t','wb') as f:
 torch.save(points, f)

In [ ]:
 points = torch.load('../data/p1ch3/ourpoints.t')

In [ ]:
 with open('../data/p1ch3/ourpoints.t','rb') as f:
 points = torch.load(f)


In [ ]:
 import h5py
 f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
 dset = f.create_dataset('coords', data=points.numpy())
 f.close(

In [ ]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
 dset = f['coords']
 last_points = dset[-2:]

In [ ]:
 # In[63]:
 last_points = torch.from_numpy(dset[-2:])
 f.close(