<a href="https://colab.research.google.com/github/SumiranRai/MDSC-Lab/blob/main/MDSC-101-Applied-Linear-Algebra/Linear_Algebra_using_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Calculating Eigenvalues, Eigenvectors, SVD  & Matrix Exponential using Numpy

In [2]:
import numpy as np

In [3]:
def get_matrix_input():
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))
    matrix = []

    print(f"Enter the elements row by row (separated by spaces):")
    for i in range(rows):
        row = list(map(float, input(f"Row {i+1}: ").split()))
        if len(row) != cols:
            print(f"Error: Row {i+1} must have {cols} elements!")
            return None
        matrix.append(row)

    return np.array(matrix)

Eigenvalues & Eigenvectors

In [4]:
def calculate_eigen(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    print("\nEigenvalues:")
    print(eigenvalues)
    print("\nEigenvectors:")
    print(eigenvectors)

Single Value Decomposition (SVD)

In [5]:
def calculate_svd(matrix):
    U, S, Vt = np.linalg.svd(matrix)
    print("\nSingular Value Decomposition:")
    print("U matrix:")
    print(U)
    print("\nSingular values:")
    print(S)
    print("\nV transpose matrix:")
    print(Vt)


Matrix Exponential

In [6]:
from scipy.linalg import expm

In [7]:
def calculate_matrix_exponential(matrix):
    matrix_exp = expm(matrix)
    print("\nMatrix Exponential:")
    print(matrix_exp)

Main Function

In [8]:
def main():
    # Get matrix from user
    matrix = get_matrix_input()
    if matrix is None:
        return

    print("\nOriginal Matrix:")
    print(matrix)

    # Perform Eigenvalue and Eigenvector calculation
    calculate_eigen(matrix)

    # Perform Singular Value Decomposition (SVD)
    calculate_svd(matrix)

    # Perform Matrix Exponential
    if matrix.shape[0] == matrix.shape[1]:
        calculate_matrix_exponential(matrix)
    else:
        print("\nMatrix Exponential is not defined for non-square matrices.")

In [9]:
# Run the default matrix operations
main()

Enter the number of rows: 2
Enter the number of columns: 2
Enter the elements row by row (separated by spaces):
Row 1: 10 17
Row 2: 24 87

Original Matrix:
[[10. 17.]
 [24. 87.]]

Eigenvalues:
[ 5.02299458 91.97700542]

Eigenvectors:
[[-0.95971616 -0.20305504]
 [ 0.28097133 -0.97916732]]

Singular Value Decomposition:
U matrix:
[[-0.20711146 -0.97831735]
 [-0.97831735  0.20711146]]

Singular values:
[92.24378164  5.00846769]

V transpose matrix:
[[-0.27699137 -0.96087241]
 [-0.96087241  0.27699137]]

Matrix Exponential:
[[5.04410837e+38 1.72292041e+39]
 [2.43235823e+39 8.30822683e+39]]


# Linear Regression

In [11]:
def get_vector_input():
    print("\nEnter the vector for Linear Regression (space separated):")
    try:
        return np.array(list(map(float, input().split())))
    except ValueError:
        print("Invalid input. Please enter numeric values.")
        return None

def perform_linear_regression(X, y):
    if X is None or y is None:
        print("\nError: X or y is None!")
        return

    if len(X) != len(y):
        print("\nError: The number of rows in X and elements in y must be the same!")
        return

    # Add a column of ones for the intercept term (X becomes 2D)
    X_b = np.c_[np.ones((len(X), 1)), X]  # Add intercept term

    try:
        # Compute the best-fit coefficients using the normal equation
        theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)
        print("\nLinear Regression Coefficients (intercept and slope):")
        print(theta_best)
    except np.linalg.LinAlgError:
        print("\nError: Matrix inversion failed. Check if X'X is invertible.")

def linear_regression_module():
    print("\n--- Linear Regression Module ---")

    # Get feature matrix (X) and target vector (y) from the user
    X = get_matrix_input()  # Assuming this function is defined elsewhere
    if X is None:
        return

    y = get_vector_input()
    if y is None:
        return

    perform_linear_regression(X, y)

linear_regression_module()


--- Linear Regression Module ---
Enter the number of rows: 2
Enter the number of columns: 2
Enter the elements row by row (separated by spaces):
Row 1: 12 44
Row 2: 32 87

Enter the vector for Linear Regression (space separated):
23 84

Linear Regression Coefficients (intercept and slope):
[-134.        4.6875   -1.375 ]
