<a href="https://colab.research.google.com/github/SumiranRai/MDSC-Lab/blob/main/MDSC-201-Statistical-Methods-Using-R/R_Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

R Programming Assignment III

By Sumiran Rai

Roll No: 24040208007

# R Functions

##Basic Operations

In [302]:
# 1. Create a vector
x <- c(1, 2, 3, 4)
print(x)

[1] 1 2 3 4


In [303]:
# 2. Generate sequences
y <- seq(1, 10, by = 2)
print(y)

[1] 1 3 5 7 9


In [304]:
# 3. Repeat elements
z <- rep(1:3, each = 2)
print(z)

[1] 1 1 2 2 3 3


In [305]:
# 4. Get vector length
length(x)

[1] 4

In [306]:
# 5. Sort values
sort(c(3, 1, 4, 1, 5))

[1] 1 1 3 4 5

The order() function takes one or more vectors as arguments,
and returns an integer vector indicating the order of the vectors

In [307]:
# 6. Get ordering
order(c(3, 1, 4, 1, 5))

[1] 2 4 1 3 5

In [308]:
# 7. Reverse elements
rev(x)

[1] 4 3 2 1

In [309]:
# 8. Find unique elements
unique(c(1, 2, 2, 3, 3, 4))

[1] 1 2 3 4

In [310]:
# 9. Frequency table
table(c("A", "B", "A", "C", "B", "A"))


A B C 
3 2 1 

In [311]:
# 10. Find indices of matching values
match(2, c(1, 3, 5, 2, 4))

[1] 4

In [312]:
# 11. Check if value exists in vector
2 %in% c(1, 2, 3, 4)

[1] TRUE

In [313]:
# 12. Find index of elements satisfying a condition
which(c(1, 2, 3, 4) > 2)

[1] 3 4

In [314]:
# 13. Check if any value is TRUE
any(c(FALSE, TRUE, FALSE))

[1] TRUE

In [315]:
# 14. Check if all values are TRUE
all(c(TRUE, TRUE, TRUE))

[1] TRUE

In [316]:
# 15. Check for missing values
is.na(c(1, 2, NA, 4))

[1] FALSE FALSE  TRUE FALSE

In [317]:
# 16. Remove NA values
na.omit(c(1, 2, NA, 4))

[1] 1 2 4
attr(,"na.action")
[1] 3
attr(,"class")
[1] "omit"

In [318]:
# 17. Replace values in a vector
replace(c(1, 2, 3, 2), 2, 10)

[1]  1 10  3  2

In [319]:
# 18. Concatenate strings
paste("Hello", "World")

[1] "Hello World"

In [320]:
# 19. Concatenate without spaces
paste0("Hello", "World")

[1] "HelloWorld"

In [321]:
 # 20. Convert to uppercase
 toupper("hello")

[1] "HELLO"

In [322]:
# 21. Convert to lowercase
tolower("HELLO")

[1] "hello"

In [323]:
# 22. Extract substring
substr("HelloWorld", 2, 5)

[1] "ello"

In [324]:
# 23. Pattern matching
grep("a", c("apple", "banana", "cherry"))

[1] 1 2

In [325]:
# 24. Replace pattern
gsub("a", "@", "banana")

[1] "b@n@n@"

In [326]:
# 25. Split strings
strsplit("apple,banana,grape", ",")

[[1]]
[1] "apple"  "banana" "grape"

In [327]:
 # 26. Convert to numeric
as.numeric("10")

[1] 10

In [328]:
# 27. Convert to character
as.character(10)

[1] "10"

In [329]:
# 28. Convert to factor
as.factor(c("low", "medium", "high"))

[1] low    medium high  
Levels: high low medium

In [330]:
 # 29. Convert to date
as.Date("2024-02-05")

[1] "2024-02-05"

In [331]:
 # 30. Get current date
Sys.Date()

[1] "2025-02-05"

## Mathematical & Statistical Functions

In [332]:
# 31. Sum of elements
sum(c(1, 2, 3))  # Sum of elements

[1] 6

In [333]:
# 32. Product of elements
prod(c(1, 2, 3))

[1] 6

In [334]:
# 33. Cumulative sum
cumsum(c(1, 2, 3))

[1] 1 3 6

In [335]:
# 34. Cumulative product
cumprod(c(1, 2, 3))

[1] 1 2 6

In [336]:
 # 35. Compute mean
mean(c(1, 2, 3))

[1] 2

In [337]:
median(c(1, 2, 3, 4))  # Compute median

[1] 2.5

In [338]:
min(c(1, 2, 3))  # Find minimum

[1] 1

In [339]:

max(c(1, 2, 3))  # Find maximum

[1] 3

In [340]:
range(c(1, 2, 3))  # Find range

[1] 1 3

In [341]:
var(c(1, 2, 3))  # Variance

[1] 1

In [342]:
sd(c(1, 2, 3))  # Standard deviation

[1] 1

In [343]:

cov(c(1, 2, 3), c(3, 2, 1))  # Covariance

[1] -1

In [344]:
cor(c(1, 2, 3), c(3, 2, 1))  # Correlation coefficient

[1] -1

In [345]:
quantile(c(1, 2, 3, 4, 5), probs = 0.5)  # Compute quantiles

50% 
  3

In [346]:

round(3.14159, 2)  # Round values

[1] 3.14

In [347]:
ceiling(3.2)  # Round up

[1] 4

In [348]:
floor(3.9)  # Round down

[1] 3

In [349]:
abs(-5)  # Absolute value

[1] 5

In [350]:
sqrt(9)  # Square root

[1] 3

In [351]:
log(10)  # Natural logarithm

[1] 2.302585

In [352]:
exp(2)  # Exponential function

[1] 7.389056

In [353]:

factorial(5)  # Compute factorial

[1] 120

In [354]:
choose(5, 2)  # Compute binomial coefficient

[1] 10

In [355]:
sin(pi/2)  # Sine function

[1] 1

In [356]:
cos(0)  # Cosine function

[1] 1

In [357]:

tan(pi/4)  # Tangent function

[1] 1

## Data Manipulation

In [359]:
df <- data.frame(A = 1:3, B = c("x", "y", "z"))  # Create data frame

In [360]:
lst <- list(a = 1, b = "hello")  # Create a list

In [361]:

mat <- matrix(1:9, nrow = 3)  # Create a matrix

In [362]:
arr <- array(1:8, dim = c(2, 2, 2))  # Create an array

In [363]:

t(mat)  # Transpose a matrix

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [364]:

rbind(1:3, 4:6)  # Row bind data

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [365]:
cbind(1:3, 4:6)  # Column bind data

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [366]:

dim(mat)  # Get dimensions of matrix/dataframe

[1] 3 3

In [367]:
nrow(df)  # Number of rows

[1] 3

In [368]:
ncol(df)  # Number of columns

[1] 2

In [369]:
names(df)  # Get or set column names

[1] "A" "B"

In [370]:
colnames(df)  # Get/set column names

[1] "A" "B"

In [371]:
rownames(df)  # Get/set row names

[1] "1" "2" "3"

In [372]:

subset(df, A > 1)  # Subset data

A B
2 2 y
3 3 z

In [373]:
merge(data.frame(ID = 1:2), data.frame(ID = 2:3, Value = c("A", "B")))  # Merge data frames

ID Value
1 2  A

In [374]:
apply(mat, 1, sum)  # Apply function over array margins

[1] 12 15 18

In [375]:

lapply(lst, class)  # Apply function over list

$a
[1] "numeric"

$b
[1] "character"

In [376]:
sapply(lst, class)  # Simplified apply over list

a           b 
  "numeric" "character"

In [377]:

tapply(1:10, rep(1:2, each = 5), sum)  # Apply function over subsets

1  2 
15 40

In [378]:

aggregate(A ~ B, df, sum)  # Aggregate data

B A
1 x 1
2 y 2
3 z 3

In [379]:

split(1:10, rep(1:2, each = 5))  # Split data into groups

$`1`
[1] 1 2 3 4 5

$`2`
[1]  6  7  8  9 10

In [380]:
stack(df)  # Stack dataframe columns

values ind
1 1      A  
2 2      A  
3 3      A  
4 x      B  
5 y      B  
6 z      B

In [381]:
unstack(stack(df))  # Unstack stacked data

A B
1 1 x
2 2 y
3 3 z

In [382]:

reshape(df, varying = list(1:2), direction = "long")  # Reshape data

time A id
1.1 1    1 1 
2.1 1    2 2 
3.1 1    3 3 
1.2 2    x 1 
2.2 2    y 2 
3.2 2    z 3

## Control Flow & Programming

In [383]:
ifelse(c(1, 2, 3) > 2, "big", "small")  # Vectorized conditional statement

[1] "small" "small" "big"

In [384]:
for(i in 1:5) print(i)  # Loop over sequence

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [385]:
i <- 1; while(i <= 3) { print(i); i <- i + 1 }  # Loop while condition holds

[1] 1
[1] 2
[1] 3


In [386]:
repeat { print("Looping"); break }  # Infinite loop (until break)

[1] "Looping"


In [387]:
return(10)  # Return value from function

[1] 10

In [388]:
stop("Error!")  # Halt execution with error

ERROR: Error: Error!


In [389]:
warning("Warning!")  # Generate a warning message

Warning message:
“Warning!”


In [390]:
try(log("A"))  # Catch errors

Error in log("A") : non-numeric argument to mathematical function


In [391]:
tryCatch(log("A"), error = function(e) print("Error handled"))  # Advanced error handling

[1] "Error handled"


## Working with Files

In [392]:
getwd()  # Get working directory

[1] "/content/sample_data"

In [393]:
setwd("/content/sample_data")  # Set working directory

In [394]:
list.files()  # List files in directory

[1] "anscombe.json"                "california_housing_test.csv" 
[3] "california_housing_train.csv" "data.csv"                    
[5] "data.rds"                     "mnist_test.csv"              
[7] "mnist_train_small.csv"        "README.md"

In [395]:
file.exists("file.txt")  # Check if file exists

[1] FALSE

In [396]:
file.remove("file.txt")  # Delete a file

Warning message in file.remove("file.txt"):
“cannot remove file 'file.txt', reason 'No such file or directory'”


[1] FALSE

In [397]:
write.csv(df, "data.csv")  # Write CSV file

In [398]:

saveRDS(df, "data.rds")  # Save R object

In [399]:

readRDS("data.rds")  # Read R object

A B
1 1 x
2 2 y
3 3 z

 ## Date & Time Handling

In [400]:
as.POSIXct("2024-02-05 10:00:00")  # Convert to date-time format
difftime(Sys.time(), as.POSIXct("2024-02-01"))  # Compute time difference
format(Sys.Date(), "%B %d, %Y")  # Format dates


[1] "2024-02-05 10:00:00 UTC"

Time difference of 370.3327 days

[1] "February 05, 2025"