<a href="https://colab.research.google.com/github/SumiranRai/MDSC-Lab/blob/main/MDSC-201-Statistical-Methods-Using-R/R_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

R Programming Assignment I

By Sumiran Rai

Roll No: 24040208007

# R Basics

### Vectors

In [40]:
# Vector of strings
fruits <- c("banana", "apple", "orange")
# Print fruits
print("Vector of fruits:")
print(fruits)

[1] "Vector of fruits:"
[1] "banana" "apple"  "orange"


In [41]:
# Vector of numerical values
numbers <- c(1, 2, 3)
# Print numbers
print("Vector of numbers:")
print(numbers)

[1] "Vector of numbers:"
[1] 1 2 3


In [42]:
# Vector with numerical values in a sequence
num <- 1:10
# Print sequence
print("Sequence of numbers:")
print(num)

[1] "Sequence of numbers:"
 [1]  1  2  3  4  5  6  7  8  9 10


In [43]:
# Vector of logical values
log_values <- c(TRUE, FALSE, TRUE, FALSE)
# Print logical values
print("Vector of logical values:")
print(log_values)

[1] "Vector of logical values:"
[1]  TRUE FALSE  TRUE FALSE


In [44]:
# Vector Length
print("Length of the fruits vector:")
print(length(fruits))

[1] "Length of the fruits vector:"
[1] 3


In [45]:
# Sort a Vector
fruits <- c("banana", "apple", "orange", "mango", "lemon")
numbers <- c(13, 3, 5, 7, 20, 2)
print("Sorted fruits:")
print(sort(fruits))
print("Sorted numbers:")
print(sort(numbers))

[1] "Sorted fruits:"
[1] "apple"  "banana" "lemon"  "mango"  "orange"
[1] "Sorted numbers:"
[1]  2  3  5  7 13 20


In [46]:
# Access Vectors
fruits <- c("banana", "apple", "orange")
print("Access first fruit:")
print(fruits[1])
print("Access first and third fruits:")
print(fruits[c(1, 3)])

[1] "Access first fruit:"
[1] "banana"
[1] "Access first and third fruits:"
[1] "banana" "orange"


### Lists

In [47]:
# List of strings
thislist <- list("apple", "banana", "cherry")
# Print the list
print("Original list:")
print(thislist)

[1] "Original list:"
[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"



In [48]:
# Access List Items
print("Access first item in the list:")
print(thislist[1])

[1] "Access first item in the list:"
[[1]]
[1] "apple"



In [49]:
# Change Item Value
thislist[1] <- "blackcurrant"
# Print updated list
print("Updated list:")
print(thislist)

[1] "Updated list:"
[[1]]
[1] "blackcurrant"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"



In [50]:
# List Length
print("Length of the list:")
print(length(thislist))

[1] "Length of the list:"
[1] 3


In [51]:
# Join Two Lists
list1 <- list("a", "b", "c")
list2 <- list(1, 2, 3)
list3 <- c(list1, list2)
print("Combined list:")
print(list3)

[1] "Combined list:"
[[1]]
[1] "a"

[[2]]
[1] "b"

[[3]]
[1] "c"

[[4]]
[1] 1

[[5]]
[1] 2

[[6]]
[1] 3



### Matrices

In [52]:
# Create a matrix
thismatrix <- matrix(c(1, 2, 3, 4, 5, 6), nrow = 3, ncol = 2)
# Print the matrix
print("Matrix of numbers:")
print(thismatrix)

[1] "Matrix of numbers:"
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6


In [53]:
# Access Matrix Items
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)
print("Matrix of strings:")
print(thismatrix)
print("Access specific item (row 1, column 2):")
print(thismatrix[1, 2])


[1] "Matrix of strings:"
     [,1]     [,2]    
[1,] "apple"  "cherry"
[2,] "banana" "orange"
[1] "Access specific item (row 1, column 2):"
[1] "cherry"


In [54]:
# Number of Rows and Columns
print("Dimensions of the matrix:")
print(dim(thismatrix))

[1] "Dimensions of the matrix:"
[1] 2 2


In [55]:
# Matrix Length
print("Length of the matrix:")
print(length(thismatrix))

[1] "Length of the matrix:"
[1] 4


### Arrays

In [56]:
# Create a 1D array
thisarray <- c(1:10)
print("1D Array:")
print(thisarray)

[1] "1D Array:"
 [1]  1  2  3  4  5  6  7  8  9 10


In [57]:
# Create a multidimensional array
multiarray <- array(thisarray, dim = c(4, 3, 2))
print("Multidimensional Array:")
print(multiarray)

[1] "Multidimensional Array:"
, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7    1
[4,]    4    8    2

, , 2

     [,1] [,2] [,3]
[1,]    3    7    1
[2,]    4    8    2
[3,]    5    9    3
[4,]    6   10    4



In [58]:
# Access Array Items
print("Access specific item (row 2, column 3, depth 2):")
print(multiarray[2, 3, 2])

[1] "Access specific item (row 2, column 3, depth 2):"
[1] 2


In [59]:
# Amount of Rows and Columns
print("Dimensions of the multidimensional array:")
print(dim(multiarray))

[1] "Dimensions of the multidimensional array:"
[1] 4 3 2


In [60]:
# Array Length
print("Length of the array:")
print(length(multiarray))

[1] "Length of the array:"
[1] 24


### Data Frames

In [61]:
# Create a data frame
print("Original Data Frame:")
df <- data.frame(
  ID = c(1, 2, 3),
  Name = c("Student1", "Student2", "Student3"),
  Score = c(95, 89, 76),
  Passed = c(TRUE, TRUE, FALSE)
)
print(df)

[1] "Original Data Frame:"
  ID     Name Score Passed
1  1 Student1    95   TRUE
2  2 Student2    89   TRUE
3  3 Student3    76  FALSE


In [62]:
# Summarize the Data Frame
print("Summary of the data frame:")
print(summary(df))

[1] "Summary of the data frame:"
       ID          Name               Score         Passed       
 Min.   :1.0   Length:3           Min.   :76.00   Mode :logical  
 1st Qu.:1.5   Class :character   1st Qu.:82.50   FALSE:1        
 Median :2.0   Mode  :character   Median :89.00   TRUE :2        
 Mean   :2.0                      Mean   :86.67                  
 3rd Qu.:2.5                      3rd Qu.:92.00                  
 Max.   :3.0                      Max.   :95.00                  


In [63]:
# Add Rows
new_row <- rbind(df, c(4, "Student4", 88, TRUE))
print("Data Frame after adding a row:")
print(new_row)

[1] "Data Frame after adding a row:"
  ID     Name Score Passed
1  1 Student1    95   TRUE
2  2 Student2    89   TRUE
3  3 Student3    76  FALSE
4  4 Student4    88   TRUE


In [64]:
# Add Columns
new_col <- cbind(df, Year = c("1 year", "2 year", "3 year"))
print("Data Frame after adding a column:")
print(new_col)

[1] "Data Frame after adding a column:"
  ID     Name Score Passed   Year
1  1 Student1    95   TRUE 1 year
2  2 Student2    89   TRUE 2 year
3  3 Student3    76  FALSE 3 year


In [65]:
# Amount of Rows and Columns
print("Dimensions of the data frame:")
print(dim(df))

[1] "Dimensions of the data frame:"
[1] 3 4


In [66]:
# Data Frame Length
print("Length of the data frame:")
print(length(df))

[1] "Length of the data frame:"
[1] 4


In [67]:
# Combine Data Frames
df1 <- data.frame(
  ID = c(1, 2, 3),
  Name = c("Student1", "Student2", "Student3"),
  Score = c(95, 89, 76),
  Passed = c(TRUE, TRUE, FALSE)
)

df2 <- data.frame(
  ID = c(4, 5, 6),
  Name = c("Student4", "Student5", "Student6"),
  Score = c(95, 89, 76),
  Passed = c(TRUE, TRUE, FALSE)
)

New_df <- rbind(df1, df2)
print("Combined Data Frame:")
print(New_df)

[1] "Combined Data Frame:"
  ID     Name Score Passed
1  1 Student1    95   TRUE
2  2 Student2    89   TRUE
3  3 Student3    76  FALSE
4  4 Student4    95   TRUE
5  5 Student5    89   TRUE
6  6 Student6    76  FALSE


### Factors

In [68]:
# Create a vector and factor
apple_color <- c("red", "yellow", "green", "orange", "violet")
factor_apple <- factor(apple_color)

In [69]:
# Print the factor
print("Factor of apple colors:")
print(factor_apple)


[1] "Factor of apple colors:"
[1] red    yellow green  orange violet
Levels: green orange red violet yellow


In [70]:
# Print number of levels
print("Number of levels in the factor:")
print(nlevels(factor_apple))

[1] "Number of levels in the factor:"
[1] 5


In [71]:
# Factor Length
print("Length of the factor:")
print(length(factor_apple))

[1] "Length of the factor:"
[1] 5


In [72]:
# Access Factors
print("Access second level in the factor:")
print(factor_apple[2])

[1] "Access second level in the factor:"
[1] yellow
Levels: green orange red violet yellow
