<a href="https://colab.research.google.com/github/SumiranRai/MDSC-Lab/blob/main/MDSC-201-Statistical-Methods-Using-R/R_Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

R Programming Assignment III

By Sumiran Rai

Roll No: 24040208007

# R Functions

##Basic Operations

In [ ]:
# 1. Create a vector
x <- c(1, 2, 3, 4)
print(x)

[1] 1 2 3 4


In [ ]:
# 2. Generate sequences
y <- seq(1, 10, by = 2)
print(y)

[1] 1 3 5 7 9


In [ ]:
# 3. Repeat elements
z <- rep(1:3, each = 2)
print(z)

[1] 1 1 2 2 3 3


In [ ]:
# 4. Get vector length
length(x)

[1] 4

In [ ]:
# 5. Sort values
sort(c(3, 1, 4, 1, 5))

[1] 1 1 3 4 5

The order() function takes one or more vectors as arguments,
and returns an integer vector indicating the order of the vectors

In [ ]:
# 6. Get ordering
order(c(3, 1, 4, 1, 5))

[1] 2 4 1 3 5

In [ ]:
# 7. Reverse elements
rev(x)

[1] 4 3 2 1

In [ ]:
# 8. Find unique elements
unique(c(1, 2, 2, 3, 3, 4))

[1] 1 2 3 4

In [ ]:
# 9. Frequency table
table(c("A", "B", "A", "C", "B", "A"))


A B C 
3 2 1 

In [ ]:
# 10. Find indices of matching values
match(2, c(1, 3, 5, 2, 4))

[1] 4

In [ ]:
# 11. Check if value exists in vector
2 %in% c(1, 2, 3, 4)

[1] TRUE

In [ ]:
# 12. Find index of elements satisfying a condition
which(c(1, 2, 3, 4) > 2)

[1] 3 4

In [ ]:
# 13. Check if any value is TRUE
any(c(FALSE, TRUE, FALSE))

[1] TRUE

In [ ]:
# 14. Check if all values are TRUE
all(c(TRUE, TRUE, TRUE))

[1] TRUE

In [25]:
# 15. Check for missing values
is.na(c(1, 2, NA, 4))

[1] FALSE FALSE  TRUE FALSE

In [26]:
# 16. Remove NA values
na.omit(c(1, 2, NA, 4))

[1] 1 2 4
attr(,"na.action")
[1] 3
attr(,"class")
[1] "omit"

In [28]:
# 17. Replace values in a vector
replace(c(1, 2, 3, 2), 2, 10)

[1]  1 10  3  2

In [29]:
# 18. Concatenate strings
paste("Hello", "World")

[1] "Hello World"

In [30]:
# 19. Concatenate without spaces
paste0("Hello", "World")

[1] "HelloWorld"

In [31]:
 # 20. Convert to uppercase
 toupper("hello")

[1] "HELLO"

In [32]:
# 21. Convert to lowercase
tolower("HELLO")

[1] "hello"

In [33]:
# 22. Extract substring
substr("HelloWorld", 2, 5)

[1] "ello"

In [34]:
# 23. Pattern matching
grep("a", c("apple", "banana", "cherry"))

[1] 1 2

In [35]:
# 24. Replace pattern
gsub("a", "@", "banana")

[1] "b@n@n@"

In [36]:
# 25. Split strings
strsplit("apple,banana,grape", ",")

[[1]]
[1] "apple"  "banana" "grape"

In [37]:
 # 26. Convert to numeric
as.numeric("10")

[1] 10

In [42]:
# 27. Convert to character
as.character(10)

[1] "10"

In [43]:
# 28. Convert to factor
as.factor(c("low", "medium", "high"))

[1] low    medium high  
Levels: high low medium

In [47]:
 # 29. Convert to date
as.Date("2024-02-05")

[1] "2024-02-05"

In [45]:
 # 30. Get current date
Sys.Date()

[1] "2025-02-05"

## Mathematical & Statistical Functions

In [48]:
sum(c(1, 2, 3))  # Sum of elements
prod(c(1, 2, 3))  # Product of elements
cumsum(c(1, 2, 3))  # Cumulative sum
cumprod(c(1, 2, 3))  # Cumulative product
mean(c(1, 2, 3))  # Compute mean
median(c(1, 2, 3, 4))  # Compute median
min(c(1, 2, 3))  # Find minimum
max(c(1, 2, 3))  # Find maximum
range(c(1, 2, 3))  # Find range
var(c(1, 2, 3))  # Variance
sd(c(1, 2, 3))  # Standard deviation
quantile(c(1, 2, 3, 4, 5), probs = 0.5)  # Compute quantiles
round(3.14159, 2)  # Round values
ceiling(3.2)  # Round up
floor(3.9)  # Round down
abs(-5)  # Absolute value
sqrt(9)  # Square root
log(10)  # Natural logarithm
exp(2)  # Exponential function
factorial(5)  # Compute factorial
choose(5, 2)  # Compute binomial coefficient
sin(pi/2)  # Sine function
cos(0)  # Cosine function
tan(pi/4)  # Tangent function
cor(c(1, 2, 3), c(3, 2, 1))  # Correlation coefficient
cov(c(1, 2, 3), c(3, 2, 1))  # Covariance


[1] 6

[1] 6

[1] 1 3 6

[1] 1 2 6

[1] 2

[1] 2.5

[1] 1

[1] 3

[1] 1 3

[1] 1

[1] 1

50% 
  3

[1] 3.14

[1] 4

[1] 3

[1] 5

[1] 3

[1] 2.302585

[1] 7.389056

[1] 120

[1] 10

[1] 1

[1] 1

[1] 1

[1] -1

[1] -1

## Data Manipulation

In [49]:
df <- data.frame(A = 1:3, B = c("x", "y", "z"))  # Create data frame
lst <- list(a = 1, b = "hello")  # Create a list
mat <- matrix(1:9, nrow = 3)  # Create a matrix
arr <- array(1:8, dim = c(2, 2, 2))  # Create an array
t(mat)  # Transpose a matrix
rbind(1:3, 4:6)  # Row bind data
cbind(1:3, 4:6)  # Column bind data
dim(mat)  # Get dimensions of matrix/dataframe
nrow(df)  # Number of rows
ncol(df)  # Number of columns
names(df)  # Get or set column names
colnames(df)  # Get/set column names
rownames(df)  # Get/set row names
subset(df, A > 1)  # Subset data
merge(data.frame(ID = 1:2), data.frame(ID = 2:3, Value = c("A", "B")))  # Merge data frames
apply(mat, 1, sum)  # Apply function over array margins
lapply(lst, class)  # Apply function over list
sapply(lst, class)  # Simplified apply over list
tapply(1:10, rep(1:2, each = 5), sum)  # Apply function over subsets
aggregate(A ~ B, df, sum)  # Aggregate data
split(1:10, rep(1:2, each = 5))  # Split data into groups
stack(df)  # Stack dataframe columns
unstack(stack(df))  # Unstack stacked data
reshape(df, varying = list(1:2), direction = "long")  # Reshape data


[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[1] 3 3

[1] 3

[1] 2

[1] "A" "B"

[1] "A" "B"

[1] "1" "2" "3"

A B
2 2 y
3 3 z

ID Value
1 2  A

[1] 12 15 18

$a
[1] "numeric"

$b
[1] "character"

a           b 
  "numeric" "character"

1  2 
15 40

B A
1 x 1
2 y 2
3 z 3

$`1`
[1] 1 2 3 4 5

$`2`
[1]  6  7  8  9 10

values ind
1 1      A  
2 2      A  
3 3      A  
4 x      B  
5 y      B  
6 z      B

A B
1 1 x
2 2 y
3 3 z

time A id
1.1 1    1 1 
2.1 1    2 2 
3.1 1    3 3 
1.2 2    x 1 
2.2 2    y 2 
3.2 2    z 3

## Control Flow & Programming

In [50]:
ifelse(c(1, 2, 3) > 2, "big", "small")  # Vectorized conditional statement
for(i in 1:5) print(i)  # Loop over sequence
i <- 1; while(i <= 3) { print(i); i <- i + 1 }  # Loop while condition holds
repeat { print("Looping"); break }  # Infinite loop (until break)
function(x) x^2  # Define a function
return(10)  # Return value from function
stop("Error!")  # Halt execution with error
warning("Warning!")  # Generate a warning message
try(log("A"))  # Catch errors
tryCatch(log("A"), error = function(e) print("Error handled"))  # Advanced error handling


[1] "small" "small" "big"

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 1
[1] 2
[1] 3
[1] "Looping"


function (x) 
x^2

[1] 10

ERROR: Error: Error!


## Working with Files

In [51]:
getwd()  # Get working directory
setwd("/path/to/folder")  # Set working directory
list.files()  # List files in directory
file.exists("file.txt")  # Check if file exists
file.remove("file.txt")  # Delete a file
write.csv(df, "data.csv")  # Write CSV file
read.csv("data.csv")  # Read CSV file
saveRDS(df, "data.rds")  # Save R object
readRDS("data.rds")  # Read R object


[1] "/content"

ERROR: Error in setwd("/path/to/folder"): cannot change working directory


 ## Date & Time Handling

In [52]:
as.POSIXct("2024-02-05 10:00:00")  # Convert to date-time format
difftime(Sys.time(), as.POSIXct("2024-02-01"))  # Compute time difference
format(Sys.Date(), "%B %d, %Y")  # Format dates


[1] "2024-02-05 10:00:00 UTC"

Time difference of 370.297 days

[1] "February 05, 2025"