<a href="https://colab.research.google.com/github/SumiranRai/MDSC-Lab/blob/main/MDSC-201-Statistical-Methods-Using-R/R_Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

R Programming Assignment III

By Sumiran Rai

Roll No: 24040208007

# R Functions

##Basic Operations

In [2]:
# 1. Create a vector
x <- c(1, 2, 3, 4)
print(x)

[1] 1 2 3 4


In [3]:
# 2. Generate sequences
y <- seq(1, 10, by = 2)
print(y)

[1] 1 3 5 7 9


In [4]:
# 3. Repeat elements
z <- rep(1:3, each = 2)
print(z)

[1] 1 1 2 2 3 3


In [5]:
# 4. Get vector length
length(x)

[1] 4

In [6]:
# 5. Sort values
sort(c(3, 1, 4, 1, 5))

[1] 1 1 3 4 5

The order() function takes one or more vectors as arguments,
and returns an integer vector indicating the order of the vectors

In [7]:
# 6. Get ordering
order(c(3, 1, 4, 1, 5))

[1] 2 4 1 3 5

In [8]:
# 7. Reverse elements
rev(x)

[1] 4 3 2 1

In [9]:
# 8. Find unique elements
unique(c(1, 2, 2, 3, 3, 4))

[1] 1 2 3 4

In [10]:
# 9. Frequency table
table(c("A", "B", "A", "C", "B", "A"))


A B C 
3 2 1 

In [11]:
# 10. Find indices of matching values
match(2, c(1, 3, 5, 2, 4))

[1] 4

In [12]:
# 11. Check if value exists in vector
2 %in% c(1, 2, 3, 4)

[1] TRUE

In [13]:
# 12. Find index of elements satisfying a condition
which(c(1, 2, 3, 4) > 2)

[1] 3 4

In [14]:
# 13. Check if any value is TRUE
any(c(FALSE, TRUE, FALSE))

[1] TRUE

In [15]:
# 14. Check if all values are TRUE
all(c(TRUE, TRUE, TRUE))

[1] TRUE

In [16]:
# 15. Check for missing values
is.na(c(1, 2, NA, 4))

[1] FALSE FALSE  TRUE FALSE

In [17]:
# 16. Remove NA values
na.omit(c(1, 2, NA, 4))

[1] 1 2 4
attr(,"na.action")
[1] 3
attr(,"class")
[1] "omit"

In [18]:
# 17. Replace values in a vector
replace(c(1, 2, 3, 2), 2, 10)

[1]  1 10  3  2

In [19]:
# 18. Concatenate strings
paste("Hello", "World")

[1] "Hello World"

In [20]:
# 19. Concatenate without spaces
paste0("Hello", "World")

[1] "HelloWorld"

In [21]:
 # 20. Convert to uppercase
 toupper("hello")

[1] "HELLO"

In [22]:
# 21. Convert to lowercase
tolower("HELLO")

[1] "hello"

In [23]:
# 22. Extract substring
substr("HelloWorld", 2, 5)

[1] "ello"

In [24]:
# 23. Pattern matching
grep("a", c("apple", "banana", "cherry"))

[1] 1 2

In [25]:
# 24. Replace pattern
gsub("a", "@", "banana")

[1] "b@n@n@"

In [26]:
# 25. Split strings
strsplit("apple,banana,grape", ",")

[[1]]
[1] "apple"  "banana" "grape"

In [27]:
 # 26. Convert to numeric
as.numeric("10")

[1] 10

In [28]:
# 27. Convert to character
as.character(10)

[1] "10"

In [29]:
# 28. Convert to factor
as.factor(c("low", "medium", "high"))

[1] low    medium high  
Levels: high low medium

In [30]:
 # 29. Convert to date
as.Date("2024-02-05")

[1] "2024-02-05"

In [31]:
 # 30. Get current date
Sys.Date()

[1] "2025-02-05"

## Mathematical & Statistical Functions

In [32]:
# 31. Sum of elements
sum(c(1, 2, 3))  # Sum of elements

[1] 6

In [33]:
# 32. Product of elements
prod(c(1, 2, 3))

[1] 6

In [34]:
# 33. Cumulative sum
cumsum(c(1, 2, 3))

[1] 1 3 6

In [35]:
# 34. Cumulative product
cumprod(c(1, 2, 3))

[1] 1 2 6

In [36]:
 # 35. Compute mean
mean(c(1, 2, 3))

[1] 2

In [37]:
# 36. Compute median
median(c(1, 2, 3, 4))

[1] 2.5

In [38]:
# 37. Find minimum
min(c(1, 2, 3))

[1] 1

In [39]:
# 38. Find maximum
max(c(1, 2, 3))

[1] 3

In [40]:
# 39. Find range
range(c(1, 2, 3))

[1] 1 3

In [41]:
# 40. Variance
var(c(1, 2, 3))

[1] 1

In [42]:
# 41. Standard deviation
sd(c(1, 2, 3))

[1] 1

In [43]:
# 42. Covariance
cov(c(1, 2, 3), c(3, 2, 1))

[1] -1

In [44]:
# 44. Correlation coefficient
cor(c(1, 2, 3), c(3, 2, 1))

[1] -1

In [45]:
# 45. Compute quantiles
quantile(c(1, 2, 3, 4, 5), probs = 0.5)

50% 
  3

In [46]:
# 46. Round values
round(3.14159, 2)

[1] 3.14

In [47]:
# 47. Round up
ceiling(3.2)

[1] 4

In [48]:
# 48. Round down
floor(3.9)

[1] 3

In [49]:
# 49. Absolute value
abs(-5)

[1] 5

In [50]:
# 50. Square root
sqrt(9)

[1] 3

In [51]:
# 51. Natural logarithm
log(10)

[1] 2.302585

In [52]:
# 52. Exponential function
exp(2)

[1] 7.389056

In [53]:
# 53. Compute factorial
factorial(5)

[1] 120

In [54]:
# 54. Compute binomial coefficient
choose(5, 2)

[1] 10

In [55]:
 # 55. Sine function
sin(pi/2)

[1] 1

In [56]:
# 56. Cosine function
cos(0)

[1] 1

In [57]:
 # 57. Tangent function
tan(pi/4)

[1] 1

## Data Manipulation

In [58]:
df <- data.frame(A = 1:3, B = c("x", "y", "z"))  # Create data frame

In [59]:
lst <- list(a = 1, b = "hello")  # Create a list

In [60]:

mat <- matrix(1:9, nrow = 3)  # Create a matrix

In [61]:
arr <- array(1:8, dim = c(2, 2, 2))  # Create an array

In [62]:

t(mat)  # Transpose a matrix

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [63]:

rbind(1:3, 4:6)  # Row bind data

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [64]:
cbind(1:3, 4:6)  # Column bind data

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [65]:

dim(mat)  # Get dimensions of matrix/dataframe

[1] 3 3

In [66]:
nrow(df)  # Number of rows

[1] 3

In [67]:
ncol(df)  # Number of columns

[1] 2

In [68]:
names(df)  # Get or set column names

[1] "A" "B"

In [69]:
colnames(df)  # Get/set column names

[1] "A" "B"

In [70]:
rownames(df)  # Get/set row names

[1] "1" "2" "3"

In [71]:

subset(df, A > 1)  # Subset data

A B
2 2 y
3 3 z

In [72]:
merge(data.frame(ID = 1:2), data.frame(ID = 2:3, Value = c("A", "B")))  # Merge data frames

ID Value
1 2  A

In [73]:
apply(mat, 1, sum)  # Apply function over array margins

[1] 12 15 18

In [74]:

lapply(lst, class)  # Apply function over list

$a
[1] "numeric"

$b
[1] "character"

In [75]:
sapply(lst, class)  # Simplified apply over list

a           b 
  "numeric" "character"

In [76]:

tapply(1:10, rep(1:2, each = 5), sum)  # Apply function over subsets

1  2 
15 40

In [77]:

aggregate(A ~ B, df, sum)  # Aggregate data

B A
1 x 1
2 y 2
3 z 3

In [78]:

split(1:10, rep(1:2, each = 5))  # Split data into groups

$`1`
[1] 1 2 3 4 5

$`2`
[1]  6  7  8  9 10

In [79]:
stack(df)  # Stack dataframe columns

values ind
1 1      A  
2 2      A  
3 3      A  
4 x      B  
5 y      B  
6 z      B

In [80]:
unstack(stack(df))  # Unstack stacked data

A B
1 1 x
2 2 y
3 3 z

In [81]:

reshape(df, varying = list(1:2), direction = "long")  # Reshape data

time A id
1.1 1    1 1 
2.1 1    2 2 
3.1 1    3 3 
1.2 2    x 1 
2.2 2    y 2 
3.2 2    z 3

## Control Flow & Programming

In [82]:
ifelse(c(1, 2, 3) > 2, "big", "small")  # Vectorized conditional statement

[1] "small" "small" "big"

In [83]:
for(i in 1:5) print(i)  # Loop over sequence

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [84]:
i <- 1; while(i <= 3) { print(i); i <- i + 1 }  # Loop while condition holds

[1] 1
[1] 2
[1] 3


In [85]:
repeat { print("Looping"); break }  # Infinite loop (until break)

[1] "Looping"


In [86]:
return(10)  # Return value from function

[1] 10

In [87]:
stop("Error!")  # Halt execution with error

ERROR: Error: Error!


In [88]:
warning("Warning!")  # Generate a warning message

Warning message:
“Warning!”


In [90]:
try(log("A"))  # Catch errors

Error in log("A") : non-numeric argument to mathematical function


In [91]:
tryCatch(log("A"), error = function(e) print("Error handled"))  # Advanced error handling

[1] "Error handled"


## Working with Files

In [92]:
getwd()  # Get working directory

[1] "/content"

In [93]:
setwd("/content/sample_data")  # Set working directory

In [94]:
list.files()  # List files in directory

[1] "anscombe.json"                "california_housing_test.csv" 
[3] "california_housing_train.csv" "mnist_test.csv"              
[5] "mnist_train_small.csv"        "README.md"

In [95]:
file.exists("file.txt")  # Check if file exists

[1] FALSE

In [96]:
file.remove("file.txt")  # Delete a file

Warning message in file.remove("file.txt"):
“cannot remove file 'file.txt', reason 'No such file or directory'”


[1] FALSE

In [97]:
write.csv(df, "data.csv")  # Write CSV file

In [98]:

saveRDS(df, "data.rds")  # Save R object

In [99]:

readRDS("data.rds")  # Read R object

A B
1 1 x
2 2 y
3 3 z

 ## Date & Time Handling

In [100]:
as.POSIXct("2024-02-05 10:00:00")  # Convert to date-time format
difftime(Sys.time(), as.POSIXct("2024-02-01"))  # Compute time difference
format(Sys.Date(), "%B %d, %Y")  # Format dates


[1] "2024-02-05 10:00:00 UTC"

Time difference of 370.4001 days

[1] "February 05, 2025"