Importing the Libraries

In [215]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Importing the Dataset

In [216]:
dataset = pd.read_csv("Data.csv")

Exploratory Data Analysis

In [217]:
dataset.shape

(10, 4)

In [218]:
print(type(dataset))

<class 'pandas.core.frame.DataFrame'>


In [219]:
dataset.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [220]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [221]:
dataset
# count, freq

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [222]:
dataset.head(3)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

In [223]:
dataset.tail(3)

Country   Age   Salary Purchased
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

shape, columns, info, describe, head, tail

In [224]:
x = dataset.iloc[: , :-1].values
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [225]:
type(x)

numpy.ndarray

In [226]:
y = dataset.iloc[ : , -1].values
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Taking Care of Missing Values

from sklearn.impute import SimpleImputer

#SimpleImputer is a class present inside the impute sub-library which is in turn present inside sklearn (main library)

Create an object of the SimpleImputer Class and replace the null values with the mean of the column

Reshaping 1D array into 2D array. Fitting the mean and using the mean to transform A.

In [227]:
from sklearn.impute import SimpleImputer

imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
A = dataset.iloc[ :, 1].values.reshape(-1, 1)
B = dataset.iloc[ :, 2].values.reshape(-1, 1)
imp_mean.fit(A)
A = imp_mean.transform(A)

#After fitting & transformation
print(A) 

[[44.        ]
 [27.        ]
 [30.        ]
 [38.        ]
 [40.        ]
 [35.        ]
 [38.77777778]
 [48.        ]
 [50.        ]
 [37.        ]]


Similarly fitting & transforming B

In [228]:
imp_mean.fit(B)
B = imp_mean.transform(B)
print(B)

[[72000.        ]
 [48000.        ]
 [54000.        ]
 [61000.        ]
 [63777.77777778]
 [58000.        ]
 [52000.        ]
 [79000.        ]
 [83000.        ]
 [67000.        ]]


Converting 2D array back to 1D and updating the dataset with the updated data.
Rounding upto 1 decimal point.

In [229]:
dataset.iloc[ :, 1] = A.ravel()
dataset.iloc[ :, 2] = B.ravel()
dataset = dataset.round(1)

dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  63777.8       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.8  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Encoding of Categorical Variables

- Label Encoding (y)
- One Hot Encoding(x - Country)

Encoding the Dependent Variable

In [230]:
x = dataset.iloc[: , :-1].values
print(x)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.8]
 ['France' 35.0 58000.0]
 ['Spain' 38.8 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]


Encoding the Independent Variable

In [231]:
#transform one column into many columns
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = ct.fit_transform(x)
print(x)
print(type(x))

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.8]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.8 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
<class 'numpy.ndarray'>


Splitting the Dataset into Training Set and Testing Set

In [232]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 3007)
print(x_train)

[[0.0 0.0 1.0 38.8 52000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 40.0 63777.8]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [233]:
print(y_train)

[0 0 1 1 1 0 0 1]


In [234]:
print(x_test)


[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 48.0 79000.0]]


In [235]:
print(y_test)

[0 1]


# Feature Scaling --> Normalization & Standardization

- Why do we want to perform Feature Scaling?
- What is the difference between Standardization and Normalization
- Perform both Standardization and Normalization on the given Dataset separately

Standardization on the given dataset

In [236]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

print(x_train)

[[-0.77459667 -0.57735027  1.29099445  0.0120205  -1.0625989 ]
 [ 1.29099445 -0.57735027 -0.77459667  0.84544186  0.85247248]
 [-0.77459667 -0.57735027  1.29099445 -1.8792049  -1.44561318]
 [-0.77459667  1.73205081 -0.77459667  0.20434851  0.06516749]
 [ 1.29099445 -0.57735027 -0.77459667 -0.59701819 -0.48807749]
 [-0.77459667 -0.57735027  1.29099445 -0.11619817 -0.20081678]
 [-0.77459667  1.73205081 -0.77459667  1.8070819   1.90576174]
 [ 1.29099445 -0.57735027 -0.77459667 -0.27647151  0.37370464]]


In [237]:
print(x_test)

[[-0.77459667  1.73205081 -0.77459667 -1.39838488 -0.87109176]
 [ 1.29099445 -0.57735027 -0.77459667  1.48653522  1.52274747]]


Normalization on the given Dataset

In [238]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

print(x_train)

[[0.         0.         1.         0.51304348 0.11428571]
 [1.         0.         0.         0.73913043 0.68571429]
 [0.         0.         1.         0.         0.        ]
 [0.         1.         0.         0.56521739 0.45079429]
 [1.         0.         0.         0.34782609 0.28571429]
 [0.         0.         1.         0.47826087 0.37142857]
 [0.         1.         0.         1.         1.        ]
 [1.         0.         0.         0.43478261 0.54285714]]


In [239]:
print(x_test)

[[0.         1.         0.         0.13043478 0.17142857]
 [1.         0.         0.         0.91304348 0.88571429]]
